### ISSUE TITLE
Input/OutputStream String ops

### ISSUE THREAD

**Issue by fommil** [stacycurl/pimpathon#195]
would be handy. Perhaps much of the File `String` support could be moved to input/output stream and then accessed via `File{Input,Output}Stream` internally.

**Comment by stacycurl** [comment]
This looks epic, I'll have a look and create some stories.

**Comment by fommil** [comment]
I keep finding myself wanting this one recently.

**Comment by stacycurl** [comment]
I'm sorry I haven't gotten around to this, would you break this into
individual stories ? i.e. one per method; it'll make it clearer and more
approachable for me. I can also start with the most important one.

Since you wanted this recently it would be handy if you could use Bintray;
is that possible ? publishing to Sonatype is hard enough that I've only
done so 5 times, there's much less ceremony for bintray.

Cheers.

On 13 April 2015 at 20:55, Sam Halliday <notifications@github.com> wrote:

> I keep finding myself wanting this one recently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stacycurl/pimpathon/issues/195#issuecomment-92479174>.
>



-- 
Stacy

**Comment by stacycurl** [comment]
Is this basically InputStream.{readString, readBytes, readLines}, OutputStream.{writeString, writeBytes, writeLines}, or were there some other methods ?

**Comment by stacycurl** [comment]
readBytes & writeBytes look questionable; readBytes because it doesn't know the length of the inputstream so would have to allocate an intermediate strucutre; writeBytes because write already exists.

So, just readString/writeString & readLines/writeLines ?

**Comment by fommil** [comment]
Byte reading would also be good, toByteArray.

**Comment by fommil** [comment]
this would be really good. I don't know why I didn't request all this stuff on Input/OutputStream in the first place. The File equivalents would just be conveniences that forward onto that.

**Comment by stacycurl** [comment]
InputStream.toByteArray is done (as part of 1.4.5)

**Comment by fommil** [comment]
cool thanks
